services:
  ros2_humble:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ros2_humble_image
    container_name: das_ros2
    privileged: true
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - HOST_USER_ID=${HOST_USER_ID:-1000}
      - HOST_GROUP_ID=${HOST_GROUP_ID:-1000}
    volumes:
      - ./das_ros2_ws:/home/user/das_ros2_ws:z
      - ./exam_project/task22_ws:/home/user/task22_ws:z
      - ./.bashrc:/home/user/.bashrc:z
      # - ./.tmux.conf:/home/user/tmux/tmux.conf:z
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    ports:
      - "8765:8765"
      - "3000:3000"
      - "9090:9090"
    tty: true
